

answer: int=int(input("what is 2+2?: "))

if answer == 4:
    print("Good Work!")
    print("Next Question")
    print("...")
    answer: int=int(input("What is 5/5? : "))
    if answer == 1:
        print("Good Work!")
        print("WINNER!!!!")
    else:
        print("GAMEOVER!!")
        print("WAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAH")
else:
    print("GAMEOVER!!")
    print("WAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAHWAH")